#!/bin/bash
# tests/unit/test-hooks-deploy-integration.sh
#
# Tests generated deploy hooks for certbot (nginx and tomcat)
# and the mod_md adapter. Main question: "Does the hook work on
# the target machine?" — we simulate what happens during certbot renew.
#
# Critical scenarios:
#   1. Deploy hook generated by nginx triggers renewed.d + post-deploy.d
#   2. Deploy hook generated by tomcat triggers renewed.d + post-deploy.d
#   3. mod_md adapter forwards "installed" event to installed.d
#   4. Deploy hook works even without run-parts in PATH
#   5. Deploy hook does not crash when certberus hooks dir is missing
#   6. Deploy hook respects CB_HOOK_TIMEOUT
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/../lib/assert.sh"
source "$HERE/../lib/env.sh"

SANDBOX="$(t_mktempdir hooks-deploy)" || exit 1
trap 't_cleanup' EXIT

t_stub_log_helpers
t_isolate_cb_dirs "$SANDBOX"

# shellcheck disable=SC1091
source "$CB_REPO_ROOT/lib/common.sh" 2>/dev/null || true
# shellcheck disable=SC1091
source "$CB_REPO_ROOT/lib/hooks.sh"

# ==========================================================================
# Prepare marker hooks in renewed.d and post-deploy.d
# ==========================================================================
setup_marker_hooks() {
    local marker_base="$1"
    mkdir -p "$CB_HOOKS_DIR/renewed.d" "$CB_HOOKS_DIR/post-deploy.d" \
             "$CB_HOOKS_DIR/installed.d"
    cat > "$CB_HOOKS_DIR/renewed.d/10-marker" <<HOOKEOF
#!/bin/bash
echo "renewed:\${CA_EVENT:-?}:\${CA_WEBSERVER:-?}:\${CA_PRIMARY_DOMAIN:-?}:\${CA_CERT_PATH:-?}:\${CA_SOURCE:-?}" > "${marker_base}-renewed"
HOOKEOF
    chmod +x "$CB_HOOKS_DIR/renewed.d/10-marker"

    cat > "$CB_HOOKS_DIR/post-deploy.d/10-marker" <<HOOKEOF
#!/bin/bash
echo "post-deploy:\${CA_EVENT:-?}:\${CA_WEBSERVER:-?}" > "${marker_base}-postdeploy"
HOOKEOF
    chmod +x "$CB_HOOKS_DIR/post-deploy.d/10-marker"

    cat > "$CB_HOOKS_DIR/installed.d/10-marker" <<HOOKEOF
#!/bin/bash
echo "installed:\${CA_EVENT:-?}:\${CA_WEBSERVER:-?}:\${CA_PRIMARY_DOMAIN:-?}:\${CA_SOURCE:-?}" > "${marker_base}-installed"
HOOKEOF
    chmod +x "$CB_HOOKS_DIR/installed.d/10-marker"
}

# ==========================================================================
# Test 1: Nginx deploy hook
# ==========================================================================
t_info "=== Nginx deploy hook ==="
# Extract the deploy hook from nginx-certbot.sh source code
# (looking for the heredoc HOOK_EOF)
NGINX_HOOK_SRC=$(sed -n '/cat > "\$hook" <<.*HOOK_EOF/,/^HOOK_EOF$/p' \
    "$CB_REPO_ROOT/webservers/nginx-certbot.sh" | sed '1d;$d')

# Verify it contains the fallback loop (not just run-parts)
assert_contains "$NGINX_HOOK_SRC" '[[ -x "$f" ]]' "nginx hook: manual loop fallback"
assert_contains "$NGINX_HOOK_SRC" '*.example|*.bak|*.disabled' "nginx hook: skip disabled"
assert_contains "$NGINX_HOOK_SRC" 'HOOK_TO' "nginx hook: timeout protection"
assert_not_contains "$NGINX_HOOK_SRC" 'run-parts' "nginx hook: no run-parts dependency"
assert_contains "$NGINX_HOOK_SRC" 'LOG="/dev/null"' "nginx hook: log fallback for inaccessible directory"

setup_marker_hooks "$SANDBOX/nginx"

# Simulate deploy hook invocation (certbot environment)
DEPLOY_HOOK="$SANDBOX/test-deploy-nginx.sh"
cat > "$DEPLOY_HOOK" <<DEOF
#!/bin/bash
set -u
# Simulated certbot variables
RENEWED_DOMAINS="test.example.com"
RENEWED_LINEAGE="/etc/letsencrypt/live/test.example.com"

# Use our test hooks dir (override /etc/certberus/hooks)
export CA_EVENT="renewed"
export CA_WEBSERVER="nginx"
export CA_PRIMARY_DOMAIN=\$(echo "\$RENEWED_DOMAINS" | awk '{print \$1}')
export CA_DOMAIN_LIST="\$RENEWED_DOMAINS"
export CA_CERT_PATH="\$RENEWED_LINEAGE/fullchain.pem"
export CA_KEY_PATH="\$RENEWED_LINEAGE/privkey.pem"
export CA_SOURCE="certbot"

HOOK_TO="\${CB_HOOK_TIMEOUT:-60}"
HAVE_TO=0; command -v timeout >/dev/null 2>&1 && HAVE_TO=1
for ev in renewed post-deploy; do
    D="$CB_HOOKS_DIR/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        if (( HAVE_TO )); then
            timeout "\$HOOK_TO" "\$f" 2>&1 || true
        else
            "\$f" 2>&1 || true
        fi
    done
done
DEOF
chmod +x "$DEPLOY_HOOK"
"$DEPLOY_HOOK" 2>/dev/null

assert_file_exists "$SANDBOX/nginx-renewed" "nginx deploy: renewed hook ran"
assert_file_exists "$SANDBOX/nginx-postdeploy" "nginx deploy: post-deploy hook ran"
if [[ -f "$SANDBOX/nginx-renewed" ]]; then
    got=$(cat "$SANDBOX/nginx-renewed")
    assert_contains "$got" "renewed:renewed:nginx:test.example.com" "nginx deploy: env propagation"
    assert_contains "$got" "certbot" "nginx deploy: CA_SOURCE=certbot"
fi

# ==========================================================================
# Test 2: Tomcat deploy hook
# ==========================================================================
t_info "=== Tomcat deploy hook ==="
setup_marker_hooks "$SANDBOX/tomcat"

DEPLOY_HOOK_TC="$SANDBOX/test-deploy-tomcat.sh"
cat > "$DEPLOY_HOOK_TC" <<DEOF
#!/bin/bash
set -u
RENEWED_DOMAINS="tomcat.example.com"
RENEWED_LINEAGE="/etc/letsencrypt/live/tomcat.example.com"

export CA_EVENT="renewed"
export CA_WEBSERVER="tomcat"
export CA_PRIMARY_DOMAIN=\$(echo "\$RENEWED_DOMAINS" | awk '{print \$1}')
export CA_DOMAIN_LIST="\$RENEWED_DOMAINS"
export CA_CERT_PATH="\$RENEWED_LINEAGE/fullchain.pem"
export CA_KEY_PATH="\$RENEWED_LINEAGE/privkey.pem"
export CA_SOURCE="certbot"

HOOK_TO="\${CB_HOOK_TIMEOUT:-60}"
HAVE_TO=0; command -v timeout >/dev/null 2>&1 && HAVE_TO=1
for ev in renewed post-deploy; do
    D="$CB_HOOKS_DIR/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        if (( HAVE_TO )); then
            timeout "\$HOOK_TO" "\$f" 2>&1 || true
        else
            "\$f" 2>&1 || true
        fi
    done
done
DEOF
chmod +x "$DEPLOY_HOOK_TC"
"$DEPLOY_HOOK_TC" 2>/dev/null

assert_file_exists "$SANDBOX/tomcat-renewed" "tomcat deploy: renewed hook ran"
assert_file_exists "$SANDBOX/tomcat-postdeploy" "tomcat deploy: post-deploy hook ran"
if [[ -f "$SANDBOX/tomcat-renewed" ]]; then
    got=$(cat "$SANDBOX/tomcat-renewed")
    assert_contains "$got" "renewed:renewed:tomcat:tomcat.example.com" "tomcat deploy: env propagation"
fi

# ==========================================================================
# Test 3: mod_md adapter (simulating MDMessageCMD invocation)
# ==========================================================================
t_info "=== mod_md adapter ==="
setup_marker_hooks "$SANDBOX/modmd"

# Write adapter to a file and run it with arguments like Apache
ADAPTER="$SANDBOX/test-adapter.sh"
cb_mod_md_adapter_body > "$ADAPTER"
chmod +x "$ADAPTER"

# Override HOOKS_DIR and LOG in the adapter to point to our sandbox
sed -i "s|HOOKS_DIR=\"/etc/certberus/hooks\"|HOOKS_DIR=\"$CB_HOOKS_DIR\"|" "$ADAPTER"
sed -i "s|LOG=\"/var/log/certberus/mod_md-events.log\"|LOG=\"$SANDBOX/mod_md-events.log\"|" "$ADAPTER"

# Run with event=installed domain=test.mod-md.cz
"$ADAPTER" installed test.mod-md.cz 2>/dev/null

assert_file_exists "$SANDBOX/modmd-installed" "mod_md adapter: installed hook ran"
if [[ -f "$SANDBOX/modmd-installed" ]]; then
    got=$(cat "$SANDBOX/modmd-installed")
    assert_contains "$got" "installed:installed:apache:test.mod-md.cz:mod_md" "mod_md adapter: env propagation"
fi

# ==========================================================================
# Test 4: mod_md adapter - unknown event sanitization
# ==========================================================================
rm -f "$SANDBOX/modmd-installed"
"$ADAPTER" '../../../etc/shadow' test.mod-md.cz 2>/dev/null; rc=$?
[[ $rc -eq 0 ]] && t_pass "mod_md adapter: unknown event exit 0 (silent)" \
    || t_fail "mod_md adapter: unknown event exit $rc"
[[ ! -f "$SANDBOX/modmd-installed" ]] && t_pass "mod_md adapter: unknown event did not trigger hook" \
    || t_fail "mod_md adapter: unknown event triggered hook"

# ==========================================================================
# Test 5: mod_md adapter - invalid domain sanitization
# ==========================================================================
"$ADAPTER" installed '../../../etc' 2>/dev/null; rc=$?
[[ $rc -eq 0 ]] && t_pass "mod_md adapter: invalid domain exit 0" \
    || t_fail "mod_md adapter: invalid domain exit $rc"

# ==========================================================================
# Test 6: Deploy hook without run-parts - hide run-parts from PATH
# ==========================================================================
t_info "=== Without run-parts ==="
setup_marker_hooks "$SANDBOX/norp"
ORIG_PATH="$PATH"
# Remove run-parts from PATH
MOCK_BIN="$SANDBOX/mock-bin"
mkdir -p "$MOCK_BIN"
# Create symlinks to everything except run-parts
for b in bash timeout awk date mkdir echo cat chmod chown; do
    p=$(command -v "$b" 2>/dev/null) && [[ -n "$p" ]] && ln -sf "$p" "$MOCK_BIN/$b" 2>/dev/null
done

NORP_HOOK="$SANDBOX/test-norp.sh"
cat > "$NORP_HOOK" <<DEOF
#!/bin/bash
set -u
# run-parts is not in PATH
export PATH="$MOCK_BIN"

export CA_EVENT="renewed"
export CA_WEBSERVER="nginx"
export CA_PRIMARY_DOMAIN="norp.example.com"
export CA_DOMAIN_LIST="norp.example.com"
export CA_CERT_PATH="/tmp/fake-cert.pem"
export CA_KEY_PATH="/tmp/fake-key.pem"
export CA_SOURCE="certbot"

HOOK_TO=5
HAVE_TO=0; command -v timeout >/dev/null 2>&1 && HAVE_TO=1
for ev in renewed post-deploy; do
    D="$CB_HOOKS_DIR/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        if (( HAVE_TO )); then
            timeout "\$HOOK_TO" "\$f" 2>&1 || true
        else
            "\$f" 2>&1 || true
        fi
    done
done
DEOF
chmod +x "$NORP_HOOK"
"$NORP_HOOK" 2>/dev/null

assert_file_exists "$SANDBOX/norp-renewed" "without run-parts: renewed hook ran"
assert_file_exists "$SANDBOX/norp-postdeploy" "without run-parts: post-deploy hook ran"

# ==========================================================================
# Test 7: Deploy hook with a hanging hook - timeout protection
# ==========================================================================
t_info "=== Deploy hook timeout ==="
mkdir -p "$CB_HOOKS_DIR/renewed.d"
cat > "$CB_HOOKS_DIR/renewed.d/99-hang" <<HOOKEOF
#!/bin/bash
sleep 60
echo "HUNG" > "$SANDBOX/hang-marker"
HOOKEOF
chmod +x "$CB_HOOKS_DIR/renewed.d/99-hang"

TIMEOUT_HOOK="$SANDBOX/test-timeout.sh"
cat > "$TIMEOUT_HOOK" <<DEOF
#!/bin/bash
export CA_EVENT="renewed" CA_WEBSERVER="nginx" CA_PRIMARY_DOMAIN="t.test"
export CA_DOMAIN_LIST="t.test" CA_CERT_PATH="" CA_KEY_PATH="" CA_SOURCE="certbot"
HOOK_TO=2
HAVE_TO=0; command -v timeout >/dev/null 2>&1 && HAVE_TO=1
for ev in renewed; do
    D="$CB_HOOKS_DIR/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        if (( HAVE_TO )); then
            timeout "\$HOOK_TO" "\$f" 2>&1 || true
        else
            "\$f" 2>&1 || true
        fi
    done
done
DEOF
chmod +x "$TIMEOUT_HOOK"

start=$SECONDS
"$TIMEOUT_HOOK" 2>/dev/null
elapsed=$((SECONDS - start))
[[ ! -f "$SANDBOX/hang-marker" ]] && t_pass "deploy timeout: hanging hook killed" \
    || t_fail "deploy timeout: hanging hook was not killed"
(( elapsed < 10 )) && t_pass "deploy timeout: time OK (${elapsed}s)" \
    || t_fail "deploy timeout: too long (${elapsed}s)"

# ==========================================================================
# Test 8: Empty hooks dir - deploy hook does not crash
# ==========================================================================
EMPTY_HOOKS="$SANDBOX/empty-hooks"
mkdir -p "$EMPTY_HOOKS/renewed.d"
EMPTY_HOOK="$SANDBOX/test-empty.sh"
cat > "$EMPTY_HOOK" <<DEOF
#!/bin/bash
export CA_EVENT="renewed" CA_WEBSERVER="nginx" CA_PRIMARY_DOMAIN="t.test"
export CA_DOMAIN_LIST="t.test" CA_CERT_PATH="" CA_KEY_PATH="" CA_SOURCE="certbot"
for ev in renewed post-deploy; do
    D="$EMPTY_HOOKS/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        "\$f" 2>&1 || true
    done
done
echo "survived"
DEOF
chmod +x "$EMPTY_HOOK"
out=$("$EMPTY_HOOK" 2>&1)
assert_contains "$out" "survived" "empty hooks dir: deploy hook does not crash"

# ==========================================================================
# Test 9: Deploy hook with inaccessible log directory - hooks MUST work
# (Bug #15 regression: >> "$LOG" fail prevents hook execution)
# ==========================================================================
t_info "=== Deploy hook with inaccessible log ==="
setup_marker_hooks "$SANDBOX/nolog"
NOLOG_DIR="$SANDBOX/readonly-log"
mkdir -p "$NOLOG_DIR"
chmod 000 "$NOLOG_DIR"

NOLOG_HOOK="$SANDBOX/test-nolog.sh"
cat > "$NOLOG_HOOK" <<DEOF
#!/bin/bash
set -u
RENEWED_DOMAINS="nolog.example.com"
RENEWED_LINEAGE="/etc/letsencrypt/live/nolog.example.com"

LOG="$NOLOG_DIR/certbot-renewal.log"
mkdir -p "\$(dirname "\$LOG")" 2>/dev/null || true
[[ -w "\$(dirname "\$LOG")" ]] || LOG="/dev/null"

export CA_EVENT="renewed"
export CA_WEBSERVER="nginx"
export CA_PRIMARY_DOMAIN=\$(echo "\$RENEWED_DOMAINS" | awk '{print \$1}')
export CA_DOMAIN_LIST="\$RENEWED_DOMAINS"
export CA_CERT_PATH="\$RENEWED_LINEAGE/fullchain.pem"
export CA_KEY_PATH="\$RENEWED_LINEAGE/privkey.pem"
export CA_SOURCE="certbot"

HOOK_TO="\${CB_HOOK_TIMEOUT:-60}"
HAVE_TO=0; command -v timeout >/dev/null 2>&1 && HAVE_TO=1
for ev in renewed post-deploy; do
    D="$CB_HOOKS_DIR/\${ev}.d"
    [[ -d "\$D" ]] || continue
    for f in "\$D"/*; do
        [[ -x "\$f" ]] || continue
        case "\$f" in *.example|*.bak|*.disabled) continue ;; esac
        if (( HAVE_TO )); then
            timeout "\$HOOK_TO" "\$f" >> "\$LOG" 2>&1 || true
        else
            "\$f" >> "\$LOG" 2>&1 || true
        fi
    done
done
DEOF
chmod +x "$NOLOG_HOOK"
"$NOLOG_HOOK" 2>/dev/null

# Clean up readonly directory
chmod 755 "$NOLOG_DIR" 2>/dev/null

assert_file_exists "$SANDBOX/nolog-renewed" "inaccessible log: renewed hook MUST run"
assert_file_exists "$SANDBOX/nolog-postdeploy" "inaccessible log: post-deploy hook MUST run"
if [[ -f "$SANDBOX/nolog-renewed" ]]; then
    got=$(cat "$SANDBOX/nolog-renewed")
    assert_contains "$got" "renewed:renewed:nginx:nolog.example.com" "inaccessible log: env propagation"
fi

# ==========================================================================
# Test 10: mod_md adapter with inaccessible log
# ==========================================================================
t_info "=== mod_md adapter with inaccessible log ==="
setup_marker_hooks "$SANDBOX/modmd-nolog"

ADAPTER_NL="$SANDBOX/test-adapter-nolog.sh"
cb_mod_md_adapter_body > "$ADAPTER_NL"
chmod +x "$ADAPTER_NL"

NOLOG_MD_DIR="$SANDBOX/readonly-md-log"
mkdir -p "$NOLOG_MD_DIR"
chmod 000 "$NOLOG_MD_DIR"

sed -i "s|HOOKS_DIR=\"/etc/certberus/hooks\"|HOOKS_DIR=\"$CB_HOOKS_DIR\"|" "$ADAPTER_NL"
sed -i "s|LOG=\"/var/log/certberus/mod_md-events.log\"|LOG=\"$NOLOG_MD_DIR/mod_md-events.log\"|" "$ADAPTER_NL"

CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_NL" installed modmd-nolog.example.com 2>/dev/null

chmod 755 "$NOLOG_MD_DIR" 2>/dev/null

assert_file_exists "$SANDBOX/modmd-nolog-installed" "mod_md inaccessible log: installed hook MUST run"
if [[ -f "$SANDBOX/modmd-nolog-installed" ]]; then
    got=$(cat "$SANDBOX/modmd-nolog-installed")
    assert_contains "$got" "installed:installed:apache:modmd-nolog.example.com:mod_md" "mod_md inaccessible log: env propagation"
fi

t_summary
